export const CellData = [
    {
        id: 1,
        idValue : "one",
        background: "white",
    },
    {   id: 2,
        idValue : "two",
        background: "black",
    },
    {   id: 3,
        idValue : "three",
        background: "white",
    },
    {   id: 4,
        idValue : "four",   
        background: "black",
    },
    {   id: 5,
        idValue : "five",
        background: "white",
    },
    {   id: 6,
        idValue : "six",
        background: "black",
    },
    {   id: 7,
        idValue : "seven",
        background: "white",
    },
    {   id: 8,
        idValue : "eigth",
        background: "black",
    },
    {   id: 9,
        idValue : "nine",
        background: "white",
    },
    {   id: 10,
        idValue : "ten",
        background: "black",
    },
    {   id: 11,
        idValue : "eleven",
        background: "white",
    },
    {   id: 12,
        idValue : "twelve",
        background: "black",
    },
    {   id: 13,
        idValue : "thirteem",
        background: "white",
    },
    {   id: 14,
        idValue : "fourteen",
        background: "black",
    },
    {   id: 15,
        idValue : "fifteen",
        background: "white",
    },
    {   id: 16,
        idValue : "sixteen",
        background: "black",
    },
    {   id: 17,
        idValue : "seventeen",
        background: "white",
    },
    {   id: 18,
        idValue : "eigthteen",
        background: "black",
    },
    {   id: 19,
        idValue : "nineteen",
        background: "white",
    },
    {   id: 20,
        idValue : "twenty",
        background: "black",
    },
    {   id: 21,
        idValue : "twenty-one",
        background: "white",
    },
    {   id: 22,
        idValue : "twenty-two",
        background: "black",
    },
    {   id: 23,
        idValue : "twenty-three",
        background: "white",
    },
    {   id: 24,
        idValue : "twenty-four",
        background: "black",
    },
    {   id: 25,
        idValue : "twenty-five",
        background: "white",
    },
    {   id: 26,
        idValue : "twenty-six",
        background: "black",
    },
    {   id: 27,
        idValue : "twenty-seven",
        background: "white",
    },
    {   id: 28,
        idValue : "twenty-eight",
        background: "black",
    },
    {   id: 29,
        idValue : "twenty-nine",
        background: "white",
    },
    {   id: 30,
        idValue : "thirty",
        background: "black",
    },
    {   id: 31,
        idValue : "thirty-one",
        background: "white",
    },
    {   id: 32,
        idValue : "thirty-two",
        background: "black",
    },
    {   id: 33,
        idValue : "thirty-three",
        background: "white",
    },
    {   id: 34,
        idValue : "thirty-four",
        background: "black",
    },
    {   id: 35,
        idValue : "thirty-five",
        background: "white",
    },
    {   id: 36,
        idValue : "thirty-six",
        background: "black",
    },
    {   id: 37,
        idValue : "thirty-seven",
        background: "white",
    },
    {   id: 38,
        idValue : "thirty-eight",
        background: "black",
    },
    {   id: 39,
        idValue : "thirty-nine",
        background: "white",
    },
    {   id: 40,
        idValue : "forty",
        background: "black",
    },
    {   id: 41,
        idValue : "forty-one",
        background: "white",
    },
    {   id: 42,
        idValue : "forty-two",
        background: "black",
    },
    {   id: 43,
        idValue : "forty-three",
        background: "white",
    },
    {   id: 44,
        idValue : "forty-four",
        background: "black",
    },
    {   id: 45,
        idValue : "forty-five",
        background: "white",
    },
    {   id: 46,
        idValue : "forty-six",
        background: "black",
    },
    {   id: 47,
        idValue : "forty-seven",
        background: "white",
    },
    {   id: 48,
        idValue : "forty-eight",
        background: "black",
    },
    {   id: 49,
        idValue : "forty-nine",
        background: "white",
    },
    {   id: 50,
        idValue : "fifty",
        background: "black",
    },
    {   id: 51,
        idValue : "fifty-one",
        background: "white",
    },
    {   id: 52,
        idValue : "fifty-two",
        background: "black",
    },
    {   id: 53,
        idValue : "fifty-three",
        background: "white",
    },
    {   id: 54,
        idValue : "fifty-four",
        background: "black",
    },
    {   id: 55,
        idValue : "fifty-five",
        background: "white",
    },
    {   id: 56,
        idValue : "fifty-six",
        background: "black",
    },
    {   id: 57,
        idValue : "fifty-seven",
        background: "white",
    },
    {   id: 58,
        idValue : "fifty-eight",
        background: "black",
    },
    {   id: 59,
        idValue : "fifty-nine",
        background: "white",
    },
    {   id: 60,
        idValue : "sixty",
        background: "black",
    },
    {   id: 61,
        idValue : "sixty-one",
        background: "white",
    },
    {   id: 62,
        idValue : "sixty-two",
        background: "black",
    },
    {   id: 63,
        idValue : "sixty-three",
        background: "white",
    },
    {   id: 64,
        idValue : "sixty-four",
        background: "black",
    },
    {   id: 65,
        idValue : "sixty-five",
        background: "white",
    }
]
